const CHANGE_COLOR = 'CHANGE_COLOR';
const FETCH_PHOTOS_START = 'FETCH_PHOTOS_START';
const RECEIVE_PHOTOS = 'RECEIVE_PHOTOS';
const FETCH_PHOTOS_ERROR = 'FETCH_PHOTOS_ERROR';

export { CHANGE_COLOR,
         FETCH_PHOTOS_START,
         RECEIVE_PHOTOS,
         FETCH_PHOTOS_ERROR
};